sudo: false
language: rust
rust:
  - nightly
  - beta
  - 1.17.0

os:
  - linux

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash

addons:
  apt:
    packages:
      - gcc-multilib
